***Hii Welcome to numPy***

In [12]:
import numpy as np

In [2]:
my_arr=np.array([[1,2,3,4,5]])
print(my_arr)

[[1 2 3 4 5]]


In [3]:
my_arr.shape

(1, 5)

In [4]:
my_arr.dtype 

dtype('int32')

In [5]:
my_arr[0,2]

3

In [6]:
my_arr[0,2]=9


In [7]:
my_arr[0,2]

9

**Array conversion:conversion from other objects**

In [8]:
myarr=np.array([[1,2,3],[4,5,6],[6,7,8]])
myarr

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [9]:
myarr.dtype

dtype('int32')

In [10]:
myarr.size

9

In [11]:
zero=np.zeros((2,4))
zero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
zero.dtype

dtype('float64')

In [13]:
ones=np.ones((3,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
rng=np.arange(1,6)
rng

array([1, 2, 3, 4, 5])

In [15]:
rng=np.arange(1,11,2)
rng


array([1, 3, 5, 7, 9])

In [17]:
lspace=np.linspace(1,10,5)
lspace

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [18]:
lspace=np.linspace(1,5,5)
lspace

array([1., 2., 3., 4., 5.])

In [19]:
emp=np.empty((3,4))
emp

array([[1.17116553e-311, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.11260619e-306, 9.14658823e-071, 5.40130919e-038,
        1.11665620e-046],
       [2.02341027e-052, 2.56995577e+184, 8.85240167e+165,
        5.68613963e-062]])

In [20]:
emp_like=np.empty_like(lspace)

In [21]:
emp_like

array([1., 2., 3., 4., 5.])

In [22]:
 ide=np.identity(20)
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.

In [23]:
ide.shape

(20, 20)

In [41]:
rearr=np.arange(100)
rearr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [42]:
reshaped_array = rearr.reshape((4, 25))
print(reshaped_array)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24]
 [25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
  49]
 [50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
  74]
 [75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98
  99]]


In [44]:
reshaped_array = rearr.reshape((20,5))
print(reshaped_array)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]
 [70 71 72 73 74]
 [75 76 77 78 79]
 [80 81 82 83 84]
 [85 86 87 88 89]
 [90 91 92 93 94]
 [95 96 97 98 99]]


In [37]:
a = np.arange(6).reshape((3, 2))
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [14]:
array = np.array([[1, 2, 3], [4, 5, 6]])
print(array)
# Convert the array to a one-dimensional array
ravelled_array = array.ravel()
# Print the ravelled array
print(ravelled_array)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [15]:
A=np.arange(1,10).reshape(3,3)

In [16]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
A.sum(axis=0)

array([12, 15, 18])

In [18]:
A.sum(axis=1)

array([ 6, 15, 24])

In [19]:
 for i in A.flat:
     print(i)

1
2
3
4
5
6
7
8
9


In [20]:
A.ndim

2

In [21]:
 A.nbytes

36

In [22]:
A.argmax()

8

In [25]:
one_d=np.arange(1,10)
one_d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
one_d.argmin()

0

In [27]:
A.argmax(axis=1)

array([2, 2, 2], dtype=int64)

In [28]:
A.argmin(axis=0)

array([0, 0, 0], dtype=int64)

In [29]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
B=np.array([[1, 2, 0],
       [4, 7, 6],
       [5, 8, 9]])

In [35]:
B

array([[1, 2, 0],
       [4, 7, 6],
       [5, 8, 9]])

In [36]:
A+B

array([[ 2,  4,  3],
       [ 8, 12, 12],
       [12, 16, 18]])

In [37]:
A-B

array([[ 0,  0,  3],
       [ 0, -2,  0],
       [ 2,  0,  0]])

In [38]:
A*B

array([[ 1,  4,  0],
       [16, 35, 36],
       [35, 64, 81]])

In [40]:
np.sqrt(A)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [41]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
np.where(B>5)

(array([1, 1, 2, 2], dtype=int64), array([1, 2, 1, 2], dtype=int64))

In [47]:
A.itemsize

4

In [48]:
import sys

In [49]:
py_arr=[1,4,2,7]
np_arr=np.array(py_arr)

In [50]:
np_arr

array([1, 4, 2, 7])

In [51]:
sys.getsizeof(1)*len(py_arr)

112

In [52]:
np_arr.itemsize*np_arr.size

16